In [11]:
import os
import pandas as pd

# Set the absolute path to the top level directory
top_level_dir = '/home/monty/projects/football-analytics-RAG'
os.chdir(top_level_dir)

# Verify the current working directory
print("Current working directory:", os.getcwd())

# Import the QA module
#from chains.qa_module import ask_question
from chains.qa_module import ask_question

# Construct the absolute path to the CSV file
data_file_path = os.path.join(top_level_dir, 'data')

Current working directory: /home/monty/projects/football-analytics-RAG

In [12]:
df = pd.read_csv(f'{data_file_path}/url_lists/playlist_urls.csv')
df.head(3)

,url,title,youtuber,playlist_name
0,https://youtube.com/watch?v=K6QF4UQw1e4,Why Erling Haaland Is Scoring SO MANY Goals At...,FourFourTwo,FourFourTwo Analysis
1,https://youtube.com/watch?v=e6H966wHR_4,Why Teams Aren't Scared Of Liverpool Anymore,FourFourTwo,FourFourTwo Analysis
2,https://youtube.com/watch?v=a8HintfLkFQ,"Conte Sacked! Did He Fail At Tottenham, Or Did...",FourFourTwo,FourFourTwo Analysis

In [13]:
transcripts_df = pd.read_csv(f'{data_file_path}/url_lists/transcripts.csv')
transcripts_df.head(3)

,url,title,youtuber,playlist_name,video_id,transcript
0,https://youtube.com/watch?v=K6QF4UQw1e4,Why Erling Haaland Is Scoring SO MANY Goals At...,FourFourTwo,FourFourTwo Analysis,K6QF4UQw1e4,hello everybody Adam leary442 here and early h...
1,https://youtube.com/watch?v=e6H966wHR_4,Why Teams Aren't Scared Of Liverpool Anymore,FourFourTwo,FourFourTwo Analysis,e6H966wHR_4,Liverpool are rubbish they're terrible the fin...
2,https://youtube.com/watch?v=a8HintfLkFQ,"Conte Sacked! Did He Fail At Tottenham, Or Did...",FourFourTwo,FourFourTwo Analysis,a8HintfLkFQ,it's day whatever in the Antonio Conte Saga at...

In [14]:
# Define your query
query = "Is Erling haaland a good footballer?"
# Ask the question and get the answer
answer = ask_question(query, vectorstore_dir="docs/chroma/", k=5)
# Display the answer
print(answer)

 Based on the comments, it seems that Erling Haaland is considered to be a good footballer, with a high goal scoring record. However, it is not clear if he is considered to be a top player or if he has areas for improvement.

In [15]:
# Define your query
query = "Who is Ange Postecoglu?"
# Ask the question and get the answer
answer = ask_question(query, vectorstore_dir="docs/chroma/", k=5)
# Display the answer
print(answer)

 Ange Postecoglu is a manager or coach at the club, known for playing attacking football and securing deals with players such as drosen and Lucas bergall.

In [16]:
# Define your query
query = "What information do you have?"
# Ask the question and get the answer
answer = ask_question(query, vectorstore_dir="docs/chroma", k=5)
# Display the answer
print(answer)

 Tottenham Hotspur is interested in signing Federico Chiesa and have overtaken Newcastle United in talks for the deal.

In [21]:
# Define your query
query = "Why is Rodri so important in Manchester City's midfield?"
# Ask the question and get the answer
answer = ask_question(query, vectorstore_dir="docs/chroma", k=5)
# Display the answer
print(answer)

 There is no specific mention of why Rodri is important in Manchester City's midfield. However, it is implied that he is a key player and a versatile midfielder who can play a pivotal role in building up from the back, switching balls, and receiving the ball in various areas of the field.

In [22]:
# Define your query
query = "What risks are there to Ange Postecoglu's system?"
# Ask the question and get the answer
answer = ask_question(query, vectorstore_dir="docs/chroma", k=5)
# Display the answer
print(answer)

 Risks to Ange Postecoglu's system include players getting injured, the system being physically demanding, and potential flaws that could lead to teams breaking through.

In [23]:
# Define your query
query = "Tell me about Tottenham's transfers"
# Ask the question and get the answer
answer = ask_question(query, vectorstore_dir="docs/chroma", k=5)
# Display the answer
print(answer)

 Tottenham may be looking to make some early deals and take advantage of the free transfer market before the January window. There is also speculation about potential signings of a defender and goalkeeper before the transfer deadline.

In [24]:
# Define your query
query = "What kind of system is Ange Postecoglu using at Tottenham?"
# Ask the question and get the answer
answer = ask_question(query, vectorstore_dir="docs/chroma", k=5)
# Display the answer
print(answer)

 It appears that Ange Postecoglu is using a similar system to his previous team at Celtic, but adapted for the Premier League. It is described as being a "front foot" style of play.

In [25]:
# Define your query
query = "What is Phil Foden's best position?"
# Ask the question and get the answer
answer = ask_question(query, vectorstore_dir="docs/chroma", k=5)
# Display the answer
print(answer)

 Phil Foden's best position is in the middle of the park or in a number 10 role in the right hand half space. He is also effective in the penalty box.